@startuml "Diagrama relacional CRUD"

entity Mesa{
  Id Integer <<pk>>
  --
  numero varchar(10)<<NN>> <<UQ>>
 
}

entity Pedido{
  Id_Pedido Integer <<pk>>
  --
  Cliente varchar(100) <<NN>>
  --
  estado varchar(20) <<NN>>
  Id_Mesa Integer <<NN>> <<FK>>
}
entity Adicional{
  Id_Adicional Integer <<pk>>
  --
  Nombre varchar(100) <<NN>>
  Precio Integer <<NN>
}

entity OpcionPedido{
Id_opcPedido <<pk>>
--
Precio Integer <<NN>>
Tipo varchar(10) <<NN>>
--
}

entity OpcionSopa{
Id_opcSopa <<Pk>>
--
Nombre varchar(100) <<NN>>

}

entity OpcionCarne{
Id_opcCarne <<Pk>>
--
Nombre varchar(100) <<NN>>

}


entity OpcionEnsalada{
Id_opcEnsalada <<Pk>>
--
Nombre varchar(100) <<NN>>

}


entity OpcionJugo{
Id_opcJugo <<Pk>>
--
Nombre varchar(100) <<NN>>

}

entity OpcionPrincipio{
Id_opcPrincipio <<Pk>>
--
Nombre varchar(100) <<NN>>


}

Mesa ||-- --o {Pedido

Pedido ||-right-|{ PedidoAdicional
Adicional ||--|{ PedidoAdicional
@enduml
